 INSERT INTO CARDDEMO.DISPUTE_STATUS
        (DST_STATUS_CD,DST_STATUS_DESC,DST_OPEN_FLAG)
 SELECT '01','OPEN                          ','Y' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '02','UNDER REVIEW                  ','Y' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '03','PENDING MERCHANT              ','Y' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '04','RESOLVED - CREDIT ISSUED      ','N' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '05','RESOLVED - DENIED             ','N' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '06','ESCALATED                     ','Y' FROM SYSIBM.SYSDUMMY1 UNION ALL
 SELECT '09','CLOSED                        ','N' FROM SYSIBM.SYSDUMMY1
 COMMIT;
