CREATE TABLE CARDDEMO.DISPUTE_HISTORY
(   DSH_DISP_ID                    CHAR(12) NOT NULL,
    DSH_SEQ                        SMALLINT NOT NULL,
    DSH_FROM_STATUS                CHAR(2) NOT NULL,
    DSH_TO_STATUS                  CHAR(2) NOT NULL,
    DSH_CHG_TS                     TIMESTAMP NOT NULL,
    DSH_CHG_USER                   CHAR(8) NOT NULL,
    DSH_NOTE                       VARCHAR(100) NOT NULL,
    PRIMARY KEY(DSH_DISP_ID,DSH_SEQ),
    FOREIGN KEY DSH_DISP_FK (DSH_DISP_ID)
    REFERENCES CARDDEMO.DISPUTE (DISP_ID) ON DELETE CASCADE);
