CREATE TABLE CARDDEMO.DISPUTE_STATUS
(   DST_STATUS_CD                  CHAR(2) NOT NULL,
    DST_STATUS_DESC                VARCHAR(30) NOT NULL,
    DST_OPEN_FLAG                  CHAR(1) NOT NULL,
    PRIMARY KEY(DST_STATUS_CD));
