CREATE TABLE CARDDEMO.DISPUTE
(   DISP_ID                        CHAR(12) NOT NULL,
    DISP_TRAN_ID                   CHAR(16) NOT NULL,
    DISP_CARD_NUM                  CHAR(16) NOT NULL,
    DISP_AMT                       DECIMAL(11,2) NOT NULL,
    DISP_REASON_CD                 CHAR(4) NOT NULL,
    DISP_STATUS_CD                 CHAR(2) NOT NULL,
    DISP_OPEN_TS                   TIMESTAMP NOT NULL,
    DISP_LAST_UPD_TS               TIMESTAMP NOT NULL,
    DISP_DESC                      VARCHAR(100) NOT NULL,
    PRIMARY KEY(DISP_ID),
    FOREIGN KEY DISP_STATUS_FK (DISP_STATUS_CD)
    REFERENCES CARDDEMO.DISPUTE_STATUS (DST_STATUS_CD) ON DELETE RESTRICT);
